<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="roboost_mecanum_robot">

    <xacro:include filename="roboost_materials.xacro"/>

    <!-- TODO: determine values -->
    <xacro:property name="chassis_length" value="0.42"/>
    <xacro:property name="chassis_width" value="0.28"/>
    <xacro:property name="chassis_height" value="0.14"/>
    <xacro:property name="chassis_mass" value="20.0"/>
    <xacro:property name="chassis_inertia" value="4.0"/>

    <xacro:property name="wheel_radius" value="0.075"/>
    <xacro:property name="wheel_width" value="0.05"/>
    <xacro:property name="wheel_mass" value="1.0"/>
    <xacro:property name="wheel_inertia" value="0.1"/>

    <xacro:property name="wheelbase" value="0.38"/>
    <xacro:property name="track" value="0.32"/>

    
    <!--link name="world"></link-->

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>

            <origin xyz="0 0 0.05" rpy="0.0 0.0 0.0"/>

            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>

            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
        <inertial>
            <mass value="${chassis_mass}"/>
            <origin xyz="0.0 0.0 ${chassis_height / 2}" rpy="0.0 0.0 0.0"/>
            <inertia ixx="${chassis_inertia}" ixy="0.0" ixz="0.0" iyy="${chassis_inertia}" iyz="0.0" izz="${chassis_inertia}"/>
        </inertial>
    </link>
    
    <link name="wheel_front_left_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>

            <origin xyz="0.0 0.0 0.03" rpy="0.0 0.0 0.0"/>

            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>

            <origin xyz="0.0 0.0 0.03" rpy="0.0 0.0 0.0"/>
        </collision>
        <inertial>
            <mass value="1.0"/>
            <origin xyz="0.0 0.0 0.03" rpy="0.0 0.0 0.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
        </inertial>
    </link>
    
    <link name="wheel_front_right_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>

            <origin xyz="0.0 0.0 0.03" rpy="0.0 0.0 0.0"/>

            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>

            <origin xyz="0.0 0.0 0.03" rpy="0.0 0.0 0.0"/>
        </collision>
        <inertial>
            <mass value="1.0"/>
            <origin xyz="0.0 0.0 0.03" rpy="0.0 0.0 0.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
        </inertial>
    </link>

    <link name="wheel_back_left_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>

            <origin xyz="0.0 0.0 0.03" rpy="0.0 0.0 0.0"/>

            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>

            <origin xyz="0.0 0.0 0.03" rpy="0.0 0.0 0.0"/>
        </collision>
        <inertial>
            <mass value="1.0"/>
            <origin xyz="0.0 0.0 0.03" rpy="0.0 0.0 0.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
        </inertial>
    </link>

    <link name="wheel_back_right_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>

            <origin xyz="0.0 0.0 0.03" rpy="0.0 0.0 0.0"/>

            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>

            <origin xyz="0.0 0.0 0.03" rpy="0.0 0.0 0.0"/>
        </collision>
        <inertial>
            <mass value="1.0"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
        </inertial>
    </link>

    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.05"/>
            </geometry>

            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>

            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.05"/>
            </geometry>

            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
        <inertial>
            <mass value="1.0"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
        </inertial>
    </link>

    <!--joint name="world_to_chassis_joint" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint-->

    <joint name="wheel_front_left_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_front_left_link"/>
        <origin xyz="${wheelbase / 2} ${track / 2} 0.0" rpy="${pi * 3 / 2} 0.0 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit effort="1000.0" velocity="1000.0"/>
    </joint>

    <joint name="wheel_front_right_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_front_right_link"/>
        <origin xyz="${wheelbase / 2} -${track / 2} 0.0" rpy="${pi / 2} 0.0 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit effort="1000.0" velocity="1000.0"/>
    </joint>

    <joint name="wheel_back_left_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_back_left_link"/>
        <origin xyz="-${wheelbase / 2} ${track / 2} 0.0" rpy="${pi * 3 / 2} 0.0 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit effort="1000.0" velocity="1000.0"/>
    </joint>

    <joint name="wheel_back_right_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_back_right_link"/>
        <origin xyz="-${wheelbase / 2} -${track / 2} 0.0" rpy="${pi / 2} 0.0 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit effort="1000.0" velocity="1000.0"/>
    </joint>

    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="0.0 0.0 ${chassis_height}" rpy="${pi} 0.0 ${pi * 3 / 2}"/>
    </joint>
</robot>
